[package]
name = "zc-network"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
tokio = { version = "1.37", features = ["rt", "rt-multi-thread", "macros", "io-util"] }
zc-security = { path = "../zc-security" }
zc-protocol = { path = "../zc-protocol" }
sha2 = "0.11.0"
x25519-dalek = "2.0.1"
rand_core = "0.6"
get_if_addrs = "0.5.3"
futures-util = "0.3.30"
ipconfig = "0.3"

[dev-dependencies]
rcgen = "0.13"
tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "net", "time"] }
prost = "0.13"
zc-protocol = { path = "../zc-protocol" }
zstd = "0.13"
