[package]
name = "zc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29.15"
zc-protocol = { path = "../zc-protocol" }
zc-network = { path = "../zc-network" }
zc-input = { path = "../zc-input" }
prost = "0.13"
tokio = { version = "1.37", features = ["rt", "rt-multi-thread"] }
wgpu = { version = "0.19" }
bytemuck = { version = "1.15", features = ["derive"] }
pollster = "0.3"
