package com.androiddex.video

import com.androiddex.core.EventBus
import com.androiddex.core.FrameEncodedEvent
import com.androiddex.core.VideoTransport
import com.androiddex.core.EncodedVideoFrame
import com.androiddex.core.CodecType
import com.androiddex.core.FrameType
import java.util.concurrent.atomic.AtomicLong

/**
 * Bridges the decoupled EventBus back to the Network Transport.
 * Subscribes to FrameEncodedEvents generated by MediaCodec, maps them to the
 * shared EncodedVideoFrame protocol, and pipes them to the active QUIC transport.
 */
class VideoPipelineOrchestrator(
    private val eventBus: EventBus,
    private val videoTransport: VideoTransport,
    private val codecType: CodecType,
    private val width: Int,
    private val height: Int
) {
    private val sequenceGenerator = AtomicLong(0)

    init {
        // Step 1 & 2 integration: Listen to encoder output and route to transport
        eventBus.subscribe(FrameEncodedEvent::class.java, ::onFrameEncoded)
    }

    private fun onFrameEncoded(event: FrameEncodedEvent) {
        val frame = EncodedVideoFrame(
            codec = codecType,
            width = width,
            height = height,
            timestampUs = event.timestampUs,
            frameType = if (event.isKeyFrame) FrameType.KEY_FRAME else FrameType.DELTA_FRAME,
            sequenceNumber = sequenceGenerator.incrementAndGet(),
            payload = event.nalUnits
        )

        // The Transport handles serialization and UDP packetization independently
        videoTransport.sendVideoFrame(frame)
    }

    fun shutdown() {
        eventBus.unsubscribe(FrameEncodedEvent::class.java, ::onFrameEncoded)
    }
}
